version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    security_opt:
      - apparmor:unconfined
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: telzir
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
